name: schedu_remind_mobile
description: "ScheduRemind Mobile - SAAS Notification & Payment Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & API
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  get_storage: ^2.1.1
  
  # UI & Design
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Date & Time
  intl: ^0.19.0
  
  # QR Code & Payments
  qr_flutter: ^4.1.0
  
  # Utilities
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
